import turtle
t=turtle.Turtle()
t.dot(5,"yellow")
m=t.clone()
m.penup()
m.goto(50,0)
m.color('blue')
m.pendown()
m.dot(5,"blue")
n=t.clone()
n.penup()
n.goto(100,0)
n.dot(5,"green")
n.color("green")
n.pendown()
o=t.clone()
o.penup()
o.goto(150,0)
o.dot(5,"red")
o.color('red')
o.pendown()
p=t.clone()
p.penup()
p.goto(200,0)
p.dot(5,"black")
p.color('black')
p.pendown()
l=t.clone()
l.penup()
l.goto(250,0)
l.dot(5,"orange")
l.color('orange')
l.pendown()
k=t.clone()
k.penup()
k.goto(300,0)
k.dot(5,"sea green")
k.color('sea green')
k.pendown()
for i in [m,n,o,p,l,k]:
    i.left(90)
    i.speed(0)
    i.shape('circle')
for i in range(1000):
    s=i%90
    m.forward(s/2000+1)
    m.left(1)
    n.forward(s/1600+1)
    n.left(1)
    o.forward(s/50+1)
    o.left(1)
    p.forward(s/40+1)
    p.left(1)
    l.forward(s/30+1)
    l.left(1)
    k.forward(s/20+1)
    k.left(1)